oprofile, doc: Fix missing xrefs
This patch fixes the following errors:

 $ XML_CATALOG_FILES=xsl/catalog.xml xsltproc --nonet -o oprofile.html
   --stringparam version 0.9.9git .../oprofile/doc/xsl/xhtml.xsl
   .../oprofile/doc/oprofile.xml
 ERROR: xref linking to controlling has no generated link text.
 Error: no ID for constraint linkend: controlling.
 ERROR: xref linking to controlling has no generated link text.
 Error: no ID for constraint linkend: controlling.

Signed-off-by: Robert Richter <rric@kernel.org>