Incorrect arguments for open() in opjitconv.c may cause compilation error
Richard Purdie reported this problem when using compile fortification
options on a mips build of oprofile:

| In file included from /media/build1/poky/build/tmp/sysroots/qemumips/usr/include/fcntl.h:302:0,
|                  from opjitconv.c:25:
| In function 'open',
|     inlined from 'copy_dumpfile' at opjitconv.c:219:6:
| /media/build1/poky/build/tmp/sysroots/qemumips/usr/include/bits/fcntl2.h:50:4: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
|     __open_missing_mode ();
|     ^
| Makefile:440: recipe for target 'opjitconv.o' failed

The error was due to the S_IRUSR create mode being specified on the open
call instead of the O_RDONLY flag.

Signed-off-by: Maynard Johnson <maynardj@us.ibm.com>