Make the always_true function signature match its use
The GCC-8.1.1 compiler in Fedora 28 checks that the function
signatures match between the declarations and uses.  The always_true
function arguments in the declaration did not match the arguments
being passed when the function is called causing the compiler to
generate the following error wit the default compiler options:

g++ -DHAVE_CONFIG_H -I. -I..  -I ../libabi -I ../libutil -I ../libutil++ -I ../libop -I ../libdb -I ../libperf_events -I ../libpe_utils   -W -Wall -fno-common -Werror -g -O2 -MT operf_sfile.o -MD -MP -MF .deps/operf_sfile.Tpo -c -o operf_sfile.o operf_sfile.cpp
operf_sfile.cpp: In function ‘int operf_sfile_lru_clear()’:
operf_sfile.cpp:549:39: error: cast between incompatible function types from ‘int (*)()’ to ‘operf_sfile_func’ {aka ‘int (*)(operf_sfile*, void*)’} [-Werror=cast-function-type]
   for_one_sfile(sf, (operf_sfile_func)always_true, NULL);
                                       ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:457: operf_sfile.o] Error 1