Added delete operators so "make check" works with newer GCC
Newer versions of GCC generate errors that the program should define
some additional delete operators with an additional parameter when
"make check" is used.  Added the additional delete operators so GCC is
happy with the code.  The "make check" will now run to completion
instead of stopping and throwing the error below:

g++ -DHAVE_CONFIG_H -I. -I../..  -I ../../libutil++ -D SRCDIR="\"/home/wcohen/research/profiling/oprofile/oprofile/libutil++/tests/\""   -W -Wall -fno-common -Werror -g -O2 -MT utility_tests.o -MD -MP -MF .deps/utility_tests.Tpo -c -o utility_tests.o utility_tests.cpp
utility_tests.cpp:36:6: error: the program should also define ‘void operator delete(void*, std::size_t)’ [-Werror=sized-deallocation]
 void operator delete(void * p) throw()
      ^~~~~~~~
utility_tests.cpp:43:6: error: the program should also define ‘void operator delete [](void*, std::size_t)’ [-Werror=sized-deallocation]
 void operator delete[](void * p) throw()
      ^~~~~~~~
cc1plus: all warnings being treated as errors

Signed-off-by: William Cohen <wcohen@redhat.com>